version: '3.8'

services:
  client:
    image: beertaste-v2:latest
    environment:
      - NODE_ENV=production
    networks:
      - supabase_default
      - proxy-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.beertaste.rule=Host(`beertaste.miasoftware`)"
        - "traefik.http.routers.beertaste.entrypoints=websecure"
        - "traefik.http.routers.beertaste.tls.certresolver=myresolver"
        - "traefik.http.services.beertaste.loadbalancer.server.port=3000"
        - "traefik.docker.network=proxy-public"
    ports:
      - "3005:3000"

networks:
  supabase_default:
    external: true
  proxy-public:
    external: true
